GET http://localhost:8000/api/authors HTTP/1.1

###

POST http://localhost:8000/api/authors HTTP/1.1
Content-Type: application/json

{
    "name": "Testing name"
}

###

DELETE http://localhost:8000/api/authors/6064cd261f102c2ff846f13d HTTP/1.1